// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/anthanhphan/gosdk/orianna/shared/health (interfaces: Checker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_health.go -package=mocks -mock_names Checker=MockHealthChecker github.com/anthanhphan/gosdk/orianna/shared/health Checker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	health "github.com/anthanhphan/gosdk/orianna/shared/health"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthChecker is a mock of Checker interface.
type MockHealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckerMockRecorder
	isgomock struct{}
}

// MockHealthCheckerMockRecorder is the mock recorder for MockHealthChecker.
type MockHealthCheckerMockRecorder struct {
	mock *MockHealthChecker
}

// NewMockHealthChecker creates a new mock instance.
func NewMockHealthChecker(ctrl *gomock.Controller) *MockHealthChecker {
	mock := &MockHealthChecker{ctrl: ctrl}
	mock.recorder = &MockHealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthChecker) EXPECT() *MockHealthCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthChecker) Check(ctx context.Context) health.HealthCheck {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(health.HealthCheck)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockHealthCheckerMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthChecker)(nil).Check), ctx)
}

// Name mocks base method.
func (m *MockHealthChecker) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockHealthCheckerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockHealthChecker)(nil).Name))
}
