// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source=server.go -destination=mocks/mock_server.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	server "github.com/anthanhphan/gosdk/orianna/pkg/server"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthCheckManager is a mock of HealthCheckManager interface.
type MockHealthCheckManager struct {
	ctrl     *gomock.Controller
	recorder *MockHealthCheckManagerMockRecorder
	isgomock struct{}
}

// MockHealthCheckManagerMockRecorder is the mock recorder for MockHealthCheckManager.
type MockHealthCheckManagerMockRecorder struct {
	mock *MockHealthCheckManager
}

// NewMockHealthCheckManager creates a new mock instance.
func NewMockHealthCheckManager(ctrl *gomock.Controller) *MockHealthCheckManager {
	mock := &MockHealthCheckManager{ctrl: ctrl}
	mock.recorder = &MockHealthCheckManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthCheckManager) EXPECT() *MockHealthCheckManagerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthCheckManager) Check(arg0 context.Context) *server.HealthReport {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", arg0)
	ret0, _ := ret[0].(*server.HealthReport)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockHealthCheckManagerMockRecorder) Check(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthCheckManager)(nil).Check), arg0)
}

// MockShutdownManager is a mock of ShutdownManager interface.
type MockShutdownManager struct {
	ctrl     *gomock.Controller
	recorder *MockShutdownManagerMockRecorder
	isgomock struct{}
}

// MockShutdownManagerMockRecorder is the mock recorder for MockShutdownManager.
type MockShutdownManagerMockRecorder struct {
	mock *MockShutdownManager
}

// NewMockShutdownManager creates a new mock instance.
func NewMockShutdownManager(ctrl *gomock.Controller) *MockShutdownManager {
	mock := &MockShutdownManager{ctrl: ctrl}
	mock.recorder = &MockShutdownManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShutdownManager) EXPECT() *MockShutdownManagerMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockShutdownManager) Shutdown(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockShutdownManagerMockRecorder) Shutdown(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockShutdownManager)(nil).Shutdown), arg0)
}
