// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen --source=client.go -destination=./mocks/client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockClient) Add(ctx context.Context, name string, value int64, tags ...string) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, value}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Add", varargs...)
}

// Add indicates an expected call of Add.
func (mr *MockClientMockRecorder) Add(ctx, name, value any, tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, value}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockClient)(nil).Add), varargs...)
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Duration mocks base method.
func (m *MockClient) Duration(ctx context.Context, name string, start time.Time, tags ...string) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, start}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Duration", varargs...)
}

// Duration indicates an expected call of Duration.
func (mr *MockClientMockRecorder) Duration(ctx, name, start any, tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, start}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Duration", reflect.TypeOf((*MockClient)(nil).Duration), varargs...)
}

// GaugeDec mocks base method.
func (m *MockClient) GaugeDec(ctx context.Context, name string, tags ...string) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "GaugeDec", varargs...)
}

// GaugeDec indicates an expected call of GaugeDec.
func (mr *MockClientMockRecorder) GaugeDec(ctx, name any, tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GaugeDec", reflect.TypeOf((*MockClient)(nil).GaugeDec), varargs...)
}

// GaugeInc mocks base method.
func (m *MockClient) GaugeInc(ctx context.Context, name string, tags ...string) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "GaugeInc", varargs...)
}

// GaugeInc indicates an expected call of GaugeInc.
func (mr *MockClientMockRecorder) GaugeInc(ctx, name any, tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GaugeInc", reflect.TypeOf((*MockClient)(nil).GaugeInc), varargs...)
}

// Handler mocks base method.
func (m *MockClient) Handler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// Handler indicates an expected call of Handler.
func (mr *MockClientMockRecorder) Handler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handler", reflect.TypeOf((*MockClient)(nil).Handler))
}

// Histogram mocks base method.
func (m *MockClient) Histogram(ctx context.Context, name string, value float64, tags ...string) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, value}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Histogram", varargs...)
}

// Histogram indicates an expected call of Histogram.
func (mr *MockClientMockRecorder) Histogram(ctx, name, value any, tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, value}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Histogram", reflect.TypeOf((*MockClient)(nil).Histogram), varargs...)
}

// Inc mocks base method.
func (m *MockClient) Inc(ctx context.Context, name string, tags ...string) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Inc", varargs...)
}

// Inc indicates an expected call of Inc.
func (mr *MockClientMockRecorder) Inc(ctx, name any, tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockClient)(nil).Inc), varargs...)
}

// SetGauge mocks base method.
func (m *MockClient) SetGauge(ctx context.Context, name string, value float64, tags ...string) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, name, value}
	for _, a := range tags {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetGauge", varargs...)
}

// SetGauge indicates an expected call of SetGauge.
func (mr *MockClientMockRecorder) SetGauge(ctx, name, value any, tags ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, name, value}, tags...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGauge", reflect.TypeOf((*MockClient)(nil).SetGauge), varargs...)
}
