// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_engine.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	logger "github.com/anthanhphan/gosdk/logger"
	configuration "github.com/anthanhphan/gosdk/orianna/pkg/configuration"
	core "github.com/anthanhphan/gosdk/orianna/pkg/core"
	engine "github.com/anthanhphan/gosdk/orianna/pkg/engine"
	routing "github.com/anthanhphan/gosdk/orianna/pkg/routing"
	gomock "go.uber.org/mock/gomock"
)

// MockServerEngine is a mock of ServerEngine interface.
type MockServerEngine struct {
	ctrl     *gomock.Controller
	recorder *MockServerEngineMockRecorder
	isgomock struct{}
}

// MockServerEngineMockRecorder is the mock recorder for MockServerEngine.
type MockServerEngineMockRecorder struct {
	mock *MockServerEngine
}

// NewMockServerEngine creates a new mock instance.
func NewMockServerEngine(ctrl *gomock.Controller) *MockServerEngine {
	mock := &MockServerEngine{ctrl: ctrl}
	mock.recorder = &MockServerEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerEngine) EXPECT() *MockServerEngineMockRecorder {
	return m.recorder
}

// RegisterGroup mocks base method.
func (m *MockServerEngine) RegisterGroup(group routing.RouteGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterGroup", group)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterGroup indicates an expected call of RegisterGroup.
func (mr *MockServerEngineMockRecorder) RegisterGroup(group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterGroup", reflect.TypeOf((*MockServerEngine)(nil).RegisterGroup), group)
}

// RegisterMetricsHandler mocks base method.
func (m *MockServerEngine) RegisterMetricsHandler(client engine.MetricsClient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterMetricsHandler", client)
}

// RegisterMetricsHandler indicates an expected call of RegisterMetricsHandler.
func (mr *MockServerEngineMockRecorder) RegisterMetricsHandler(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterMetricsHandler", reflect.TypeOf((*MockServerEngine)(nil).RegisterMetricsHandler), client)
}

// RegisterRoutes mocks base method.
func (m *MockServerEngine) RegisterRoutes(routes ...routing.Route) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range routes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RegisterRoutes", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockServerEngineMockRecorder) RegisterRoutes(routes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockServerEngine)(nil).RegisterRoutes), routes...)
}

// SetupGlobalMiddlewares mocks base method.
func (m *MockServerEngine) SetupGlobalMiddlewares(config *configuration.MiddlewareConfig, global []core.Middleware, panicRecover, rateLimiter core.Middleware, log *logger.Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupGlobalMiddlewares", config, global, panicRecover, rateLimiter, log)
}

// SetupGlobalMiddlewares indicates an expected call of SetupGlobalMiddlewares.
func (mr *MockServerEngineMockRecorder) SetupGlobalMiddlewares(config, global, panicRecover, rateLimiter, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupGlobalMiddlewares", reflect.TypeOf((*MockServerEngine)(nil).SetupGlobalMiddlewares), config, global, panicRecover, rateLimiter, log)
}

// Shutdown mocks base method.
func (m *MockServerEngine) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockServerEngineMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockServerEngine)(nil).Shutdown), ctx)
}

// Start mocks base method.
func (m *MockServerEngine) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServerEngineMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockServerEngine)(nil).Start))
}

// Use mocks base method.
func (m *MockServerEngine) Use(middleware ...core.Middleware) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range middleware {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Use", varargs...)
}

// Use indicates an expected call of Use.
func (mr *MockServerEngineMockRecorder) Use(middleware ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockServerEngine)(nil).Use), middleware...)
}

// MockMetricsClient is a mock of MetricsClient interface.
type MockMetricsClient struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsClientMockRecorder
	isgomock struct{}
}

// MockMetricsClientMockRecorder is the mock recorder for MockMetricsClient.
type MockMetricsClientMockRecorder struct {
	mock *MockMetricsClient
}

// NewMockMetricsClient creates a new mock instance.
func NewMockMetricsClient(ctrl *gomock.Controller) *MockMetricsClient {
	mock := &MockMetricsClient{ctrl: ctrl}
	mock.recorder = &MockMetricsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsClient) EXPECT() *MockMetricsClientMockRecorder {
	return m.recorder
}

// Handler mocks base method.
func (m *MockMetricsClient) Handler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// Handler indicates an expected call of Handler.
func (mr *MockMetricsClientMockRecorder) Handler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handler", reflect.TypeOf((*MockMetricsClient)(nil).Handler))
}

// MockRouterEngine is a mock of RouterEngine interface.
type MockRouterEngine struct {
	ctrl     *gomock.Controller
	recorder *MockRouterEngineMockRecorder
	isgomock struct{}
}

// MockRouterEngineMockRecorder is the mock recorder for MockRouterEngine.
type MockRouterEngineMockRecorder struct {
	mock *MockRouterEngine
}

// NewMockRouterEngine creates a new mock instance.
func NewMockRouterEngine(ctrl *gomock.Controller) *MockRouterEngine {
	mock := &MockRouterEngine{ctrl: ctrl}
	mock.recorder = &MockRouterEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouterEngine) EXPECT() *MockRouterEngineMockRecorder {
	return m.recorder
}

// DELETE mocks base method.
func (m *MockRouterEngine) DELETE(path string, handlers ...core.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range handlers {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "DELETE", varargs...)
}

// DELETE indicates an expected call of DELETE.
func (mr *MockRouterEngineMockRecorder) DELETE(path any, handlers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, handlers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DELETE", reflect.TypeOf((*MockRouterEngine)(nil).DELETE), varargs...)
}

// GET mocks base method.
func (m *MockRouterEngine) GET(path string, handlers ...core.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range handlers {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "GET", varargs...)
}

// GET indicates an expected call of GET.
func (mr *MockRouterEngineMockRecorder) GET(path any, handlers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, handlers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GET", reflect.TypeOf((*MockRouterEngine)(nil).GET), varargs...)
}

// Group mocks base method.
func (m *MockRouterEngine) Group(prefix string, middleware ...core.Middleware) engine.RouterEngine {
	m.ctrl.T.Helper()
	varargs := []any{prefix}
	for _, a := range middleware {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Group", varargs...)
	ret0, _ := ret[0].(engine.RouterEngine)
	return ret0
}

// Group indicates an expected call of Group.
func (mr *MockRouterEngineMockRecorder) Group(prefix any, middleware ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{prefix}, middleware...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Group", reflect.TypeOf((*MockRouterEngine)(nil).Group), varargs...)
}

// HEAD mocks base method.
func (m *MockRouterEngine) HEAD(path string, handlers ...core.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range handlers {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "HEAD", varargs...)
}

// HEAD indicates an expected call of HEAD.
func (mr *MockRouterEngineMockRecorder) HEAD(path any, handlers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, handlers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HEAD", reflect.TypeOf((*MockRouterEngine)(nil).HEAD), varargs...)
}

// OPTIONS mocks base method.
func (m *MockRouterEngine) OPTIONS(path string, handlers ...core.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range handlers {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "OPTIONS", varargs...)
}

// OPTIONS indicates an expected call of OPTIONS.
func (mr *MockRouterEngineMockRecorder) OPTIONS(path any, handlers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, handlers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OPTIONS", reflect.TypeOf((*MockRouterEngine)(nil).OPTIONS), varargs...)
}

// PATCH mocks base method.
func (m *MockRouterEngine) PATCH(path string, handlers ...core.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range handlers {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PATCH", varargs...)
}

// PATCH indicates an expected call of PATCH.
func (mr *MockRouterEngineMockRecorder) PATCH(path any, handlers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, handlers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PATCH", reflect.TypeOf((*MockRouterEngine)(nil).PATCH), varargs...)
}

// POST mocks base method.
func (m *MockRouterEngine) POST(path string, handlers ...core.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range handlers {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "POST", varargs...)
}

// POST indicates an expected call of POST.
func (mr *MockRouterEngineMockRecorder) POST(path any, handlers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, handlers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "POST", reflect.TypeOf((*MockRouterEngine)(nil).POST), varargs...)
}

// PUT mocks base method.
func (m *MockRouterEngine) PUT(path string, handlers ...core.Handler) {
	m.ctrl.T.Helper()
	varargs := []any{path}
	for _, a := range handlers {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PUT", varargs...)
}

// PUT indicates an expected call of PUT.
func (mr *MockRouterEngineMockRecorder) PUT(path any, handlers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{path}, handlers...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PUT", reflect.TypeOf((*MockRouterEngine)(nil).PUT), varargs...)
}

// Use mocks base method.
func (m *MockRouterEngine) Use(middleware ...core.Middleware) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range middleware {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Use", varargs...)
}

// Use indicates an expected call of Use.
func (mr *MockRouterEngineMockRecorder) Use(middleware ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockRouterEngine)(nil).Use), middleware...)
}
