// Code generated by MockGen. DO NOT EDIT.
// Source: context.go
//
// Generated by this command:
//
//	mockgen -source=context.go -destination=mocks/mock_context.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	core "github.com/anthanhphan/gosdk/orianna/pkg/core"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestInfo is a mock of RequestInfo interface.
type MockRequestInfo struct {
	ctrl     *gomock.Controller
	recorder *MockRequestInfoMockRecorder
	isgomock struct{}
}

// MockRequestInfoMockRecorder is the mock recorder for MockRequestInfo.
type MockRequestInfoMockRecorder struct {
	mock *MockRequestInfo
}

// NewMockRequestInfo creates a new mock instance.
func NewMockRequestInfo(ctrl *gomock.Controller) *MockRequestInfo {
	mock := &MockRequestInfo{ctrl: ctrl}
	mock.recorder = &MockRequestInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestInfo) EXPECT() *MockRequestInfoMockRecorder {
	return m.recorder
}

// BaseURL mocks base method.
func (m *MockRequestInfo) BaseURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseURL indicates an expected call of BaseURL.
func (mr *MockRequestInfoMockRecorder) BaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseURL", reflect.TypeOf((*MockRequestInfo)(nil).BaseURL))
}

// Hostname mocks base method.
func (m *MockRequestInfo) Hostname() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hostname")
	ret0, _ := ret[0].(string)
	return ret0
}

// Hostname indicates an expected call of Hostname.
func (mr *MockRequestInfoMockRecorder) Hostname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hostname", reflect.TypeOf((*MockRequestInfo)(nil).Hostname))
}

// IP mocks base method.
func (m *MockRequestInfo) IP() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IP")
	ret0, _ := ret[0].(string)
	return ret0
}

// IP indicates an expected call of IP.
func (mr *MockRequestInfoMockRecorder) IP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IP", reflect.TypeOf((*MockRequestInfo)(nil).IP))
}

// Method mocks base method.
func (m *MockRequestInfo) Method() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Method")
	ret0, _ := ret[0].(string)
	return ret0
}

// Method indicates an expected call of Method.
func (mr *MockRequestInfoMockRecorder) Method() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Method", reflect.TypeOf((*MockRequestInfo)(nil).Method))
}

// OriginalURL mocks base method.
func (m *MockRequestInfo) OriginalURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OriginalURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// OriginalURL indicates an expected call of OriginalURL.
func (mr *MockRequestInfoMockRecorder) OriginalURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OriginalURL", reflect.TypeOf((*MockRequestInfo)(nil).OriginalURL))
}

// Path mocks base method.
func (m *MockRequestInfo) Path() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockRequestInfoMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockRequestInfo)(nil).Path))
}

// Protocol mocks base method.
func (m *MockRequestInfo) Protocol() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protocol")
	ret0, _ := ret[0].(string)
	return ret0
}

// Protocol indicates an expected call of Protocol.
func (mr *MockRequestInfoMockRecorder) Protocol() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protocol", reflect.TypeOf((*MockRequestInfo)(nil).Protocol))
}

// RoutePath mocks base method.
func (m *MockRequestInfo) RoutePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoutePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// RoutePath indicates an expected call of RoutePath.
func (mr *MockRequestInfoMockRecorder) RoutePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoutePath", reflect.TypeOf((*MockRequestInfo)(nil).RoutePath))
}

// Secure mocks base method.
func (m *MockRequestInfo) Secure() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secure")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Secure indicates an expected call of Secure.
func (mr *MockRequestInfoMockRecorder) Secure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secure", reflect.TypeOf((*MockRequestInfo)(nil).Secure))
}

// MockHeaderManager is a mock of HeaderManager interface.
type MockHeaderManager struct {
	ctrl     *gomock.Controller
	recorder *MockHeaderManagerMockRecorder
	isgomock struct{}
}

// MockHeaderManagerMockRecorder is the mock recorder for MockHeaderManager.
type MockHeaderManagerMockRecorder struct {
	mock *MockHeaderManager
}

// NewMockHeaderManager creates a new mock instance.
func NewMockHeaderManager(ctrl *gomock.Controller) *MockHeaderManager {
	mock := &MockHeaderManager{ctrl: ctrl}
	mock.recorder = &MockHeaderManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeaderManager) EXPECT() *MockHeaderManagerMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockHeaderManager) Append(field string, values ...string) {
	m.ctrl.T.Helper()
	varargs := []any{field}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Append", varargs...)
}

// Append indicates an expected call of Append.
func (mr *MockHeaderManagerMockRecorder) Append(field any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{field}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockHeaderManager)(nil).Append), varargs...)
}

// Get mocks base method.
func (m *MockHeaderManager) Get(key string, defaultValue ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range defaultValue {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockHeaderManagerMockRecorder) Get(key any, defaultValue ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, defaultValue...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHeaderManager)(nil).Get), varargs...)
}

// Set mocks base method.
func (m *MockHeaderManager) Set(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, value)
}

// Set indicates an expected call of Set.
func (mr *MockHeaderManagerMockRecorder) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockHeaderManager)(nil).Set), key, value)
}

// MockParamGetter is a mock of ParamGetter interface.
type MockParamGetter struct {
	ctrl     *gomock.Controller
	recorder *MockParamGetterMockRecorder
	isgomock struct{}
}

// MockParamGetterMockRecorder is the mock recorder for MockParamGetter.
type MockParamGetterMockRecorder struct {
	mock *MockParamGetter
}

// NewMockParamGetter creates a new mock instance.
func NewMockParamGetter(ctrl *gomock.Controller) *MockParamGetter {
	mock := &MockParamGetter{ctrl: ctrl}
	mock.recorder = &MockParamGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParamGetter) EXPECT() *MockParamGetterMockRecorder {
	return m.recorder
}

// AllParams mocks base method.
func (m *MockParamGetter) AllParams() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllParams")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// AllParams indicates an expected call of AllParams.
func (mr *MockParamGetterMockRecorder) AllParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllParams", reflect.TypeOf((*MockParamGetter)(nil).AllParams))
}

// Params mocks base method.
func (m *MockParamGetter) Params(key string, defaultValue ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range defaultValue {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Params", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Params indicates an expected call of Params.
func (mr *MockParamGetterMockRecorder) Params(key any, defaultValue ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, defaultValue...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Params", reflect.TypeOf((*MockParamGetter)(nil).Params), varargs...)
}

// ParamsParser mocks base method.
func (m *MockParamGetter) ParamsParser(out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParamsParser", out)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParamsParser indicates an expected call of ParamsParser.
func (mr *MockParamGetterMockRecorder) ParamsParser(out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParamsParser", reflect.TypeOf((*MockParamGetter)(nil).ParamsParser), out)
}

// MockQueryGetter is a mock of QueryGetter interface.
type MockQueryGetter struct {
	ctrl     *gomock.Controller
	recorder *MockQueryGetterMockRecorder
	isgomock struct{}
}

// MockQueryGetterMockRecorder is the mock recorder for MockQueryGetter.
type MockQueryGetterMockRecorder struct {
	mock *MockQueryGetter
}

// NewMockQueryGetter creates a new mock instance.
func NewMockQueryGetter(ctrl *gomock.Controller) *MockQueryGetter {
	mock := &MockQueryGetter{ctrl: ctrl}
	mock.recorder = &MockQueryGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryGetter) EXPECT() *MockQueryGetterMockRecorder {
	return m.recorder
}

// AllQueries mocks base method.
func (m *MockQueryGetter) AllQueries() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllQueries")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// AllQueries indicates an expected call of AllQueries.
func (mr *MockQueryGetterMockRecorder) AllQueries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllQueries", reflect.TypeOf((*MockQueryGetter)(nil).AllQueries))
}

// Query mocks base method.
func (m *MockQueryGetter) Query(key string, defaultValue ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range defaultValue {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockQueryGetterMockRecorder) Query(key any, defaultValue ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, defaultValue...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockQueryGetter)(nil).Query), varargs...)
}

// QueryParser mocks base method.
func (m *MockQueryGetter) QueryParser(out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryParser", out)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryParser indicates an expected call of QueryParser.
func (mr *MockQueryGetterMockRecorder) QueryParser(out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryParser", reflect.TypeOf((*MockQueryGetter)(nil).QueryParser), out)
}

// MockBodyParser is a mock of BodyParser interface.
type MockBodyParser struct {
	ctrl     *gomock.Controller
	recorder *MockBodyParserMockRecorder
	isgomock struct{}
}

// MockBodyParserMockRecorder is the mock recorder for MockBodyParser.
type MockBodyParserMockRecorder struct {
	mock *MockBodyParser
}

// NewMockBodyParser creates a new mock instance.
func NewMockBodyParser(ctrl *gomock.Controller) *MockBodyParser {
	mock := &MockBodyParser{ctrl: ctrl}
	mock.recorder = &MockBodyParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBodyParser) EXPECT() *MockBodyParserMockRecorder {
	return m.recorder
}

// Body mocks base method.
func (m *MockBodyParser) Body() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Body indicates an expected call of Body.
func (mr *MockBodyParserMockRecorder) Body() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockBodyParser)(nil).Body))
}

// BodyParser mocks base method.
func (m *MockBodyParser) BodyParser(out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BodyParser", out)
	ret0, _ := ret[0].(error)
	return ret0
}

// BodyParser indicates an expected call of BodyParser.
func (mr *MockBodyParserMockRecorder) BodyParser(out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BodyParser", reflect.TypeOf((*MockBodyParser)(nil).BodyParser), out)
}

// MockCookieManager is a mock of CookieManager interface.
type MockCookieManager struct {
	ctrl     *gomock.Controller
	recorder *MockCookieManagerMockRecorder
	isgomock struct{}
}

// MockCookieManagerMockRecorder is the mock recorder for MockCookieManager.
type MockCookieManagerMockRecorder struct {
	mock *MockCookieManager
}

// NewMockCookieManager creates a new mock instance.
func NewMockCookieManager(ctrl *gomock.Controller) *MockCookieManager {
	mock := &MockCookieManager{ctrl: ctrl}
	mock.recorder = &MockCookieManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCookieManager) EXPECT() *MockCookieManagerMockRecorder {
	return m.recorder
}

// ClearCookie mocks base method.
func (m *MockCookieManager) ClearCookie(key ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range key {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ClearCookie", varargs...)
}

// ClearCookie indicates an expected call of ClearCookie.
func (mr *MockCookieManagerMockRecorder) ClearCookie(key ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCookie", reflect.TypeOf((*MockCookieManager)(nil).ClearCookie), key...)
}

// Cookie mocks base method.
func (m *MockCookieManager) Cookie(cookie *core.Cookie) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cookie", cookie)
}

// Cookie indicates an expected call of Cookie.
func (mr *MockCookieManagerMockRecorder) Cookie(cookie any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cookie", reflect.TypeOf((*MockCookieManager)(nil).Cookie), cookie)
}

// Cookies mocks base method.
func (m *MockCookieManager) Cookies(key string, defaultValue ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range defaultValue {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Cookies", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Cookies indicates an expected call of Cookies.
func (mr *MockCookieManagerMockRecorder) Cookies(key any, defaultValue ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, defaultValue...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cookies", reflect.TypeOf((*MockCookieManager)(nil).Cookies), varargs...)
}

// MockResponseWriter is a mock of ResponseWriter interface.
type MockResponseWriter struct {
	ctrl     *gomock.Controller
	recorder *MockResponseWriterMockRecorder
	isgomock struct{}
}

// MockResponseWriterMockRecorder is the mock recorder for MockResponseWriter.
type MockResponseWriterMockRecorder struct {
	mock *MockResponseWriter
}

// NewMockResponseWriter creates a new mock instance.
func NewMockResponseWriter(ctrl *gomock.Controller) *MockResponseWriter {
	mock := &MockResponseWriter{ctrl: ctrl}
	mock.recorder = &MockResponseWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseWriter) EXPECT() *MockResponseWriterMockRecorder {
	return m.recorder
}

// JSON mocks base method.
func (m *MockResponseWriter) JSON(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JSON", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// JSON indicates an expected call of JSON.
func (mr *MockResponseWriterMockRecorder) JSON(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSON", reflect.TypeOf((*MockResponseWriter)(nil).JSON), data)
}

// Redirect mocks base method.
func (m *MockResponseWriter) Redirect(location string, status ...int) error {
	m.ctrl.T.Helper()
	varargs := []any{location}
	for _, a := range status {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Redirect", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Redirect indicates an expected call of Redirect.
func (mr *MockResponseWriterMockRecorder) Redirect(location any, status ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{location}, status...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redirect", reflect.TypeOf((*MockResponseWriter)(nil).Redirect), varargs...)
}

// ResponseStatusCode mocks base method.
func (m *MockResponseWriter) ResponseStatusCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseStatusCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// ResponseStatusCode indicates an expected call of ResponseStatusCode.
func (mr *MockResponseWriterMockRecorder) ResponseStatusCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseStatusCode", reflect.TypeOf((*MockResponseWriter)(nil).ResponseStatusCode))
}

// SendBytes mocks base method.
func (m *MockResponseWriter) SendBytes(b []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBytes", b)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBytes indicates an expected call of SendBytes.
func (mr *MockResponseWriterMockRecorder) SendBytes(b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBytes", reflect.TypeOf((*MockResponseWriter)(nil).SendBytes), b)
}

// SendString mocks base method.
func (m *MockResponseWriter) SendString(s string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendString", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendString indicates an expected call of SendString.
func (mr *MockResponseWriterMockRecorder) SendString(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendString", reflect.TypeOf((*MockResponseWriter)(nil).SendString), s)
}

// Status mocks base method.
func (m *MockResponseWriter) Status(status int) core.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", status)
	ret0, _ := ret[0].(core.Context)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockResponseWriterMockRecorder) Status(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockResponseWriter)(nil).Status), status)
}

// XML mocks base method.
func (m *MockResponseWriter) XML(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XML", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// XML indicates an expected call of XML.
func (mr *MockResponseWriterMockRecorder) XML(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XML", reflect.TypeOf((*MockResponseWriter)(nil).XML), data)
}

// MockContentNegotiator is a mock of ContentNegotiator interface.
type MockContentNegotiator struct {
	ctrl     *gomock.Controller
	recorder *MockContentNegotiatorMockRecorder
	isgomock struct{}
}

// MockContentNegotiatorMockRecorder is the mock recorder for MockContentNegotiator.
type MockContentNegotiatorMockRecorder struct {
	mock *MockContentNegotiator
}

// NewMockContentNegotiator creates a new mock instance.
func NewMockContentNegotiator(ctrl *gomock.Controller) *MockContentNegotiator {
	mock := &MockContentNegotiator{ctrl: ctrl}
	mock.recorder = &MockContentNegotiatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentNegotiator) EXPECT() *MockContentNegotiatorMockRecorder {
	return m.recorder
}

// Accepts mocks base method.
func (m *MockContentNegotiator) Accepts(offers ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Accepts", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Accepts indicates an expected call of Accepts.
func (mr *MockContentNegotiatorMockRecorder) Accepts(offers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accepts", reflect.TypeOf((*MockContentNegotiator)(nil).Accepts), offers...)
}

// AcceptsCharsets mocks base method.
func (m *MockContentNegotiator) AcceptsCharsets(offers ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptsCharsets", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// AcceptsCharsets indicates an expected call of AcceptsCharsets.
func (mr *MockContentNegotiatorMockRecorder) AcceptsCharsets(offers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptsCharsets", reflect.TypeOf((*MockContentNegotiator)(nil).AcceptsCharsets), offers...)
}

// AcceptsEncodings mocks base method.
func (m *MockContentNegotiator) AcceptsEncodings(offers ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptsEncodings", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// AcceptsEncodings indicates an expected call of AcceptsEncodings.
func (mr *MockContentNegotiatorMockRecorder) AcceptsEncodings(offers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptsEncodings", reflect.TypeOf((*MockContentNegotiator)(nil).AcceptsEncodings), offers...)
}

// AcceptsLanguages mocks base method.
func (m *MockContentNegotiator) AcceptsLanguages(offers ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptsLanguages", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// AcceptsLanguages indicates an expected call of AcceptsLanguages.
func (mr *MockContentNegotiatorMockRecorder) AcceptsLanguages(offers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptsLanguages", reflect.TypeOf((*MockContentNegotiator)(nil).AcceptsLanguages), offers...)
}

// MockRequestState is a mock of RequestState interface.
type MockRequestState struct {
	ctrl     *gomock.Controller
	recorder *MockRequestStateMockRecorder
	isgomock struct{}
}

// MockRequestStateMockRecorder is the mock recorder for MockRequestState.
type MockRequestStateMockRecorder struct {
	mock *MockRequestState
}

// NewMockRequestState creates a new mock instance.
func NewMockRequestState(ctrl *gomock.Controller) *MockRequestState {
	mock := &MockRequestState{ctrl: ctrl}
	mock.recorder = &MockRequestStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestState) EXPECT() *MockRequestStateMockRecorder {
	return m.recorder
}

// Fresh mocks base method.
func (m *MockRequestState) Fresh() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fresh")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Fresh indicates an expected call of Fresh.
func (mr *MockRequestStateMockRecorder) Fresh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fresh", reflect.TypeOf((*MockRequestState)(nil).Fresh))
}

// Stale mocks base method.
func (m *MockRequestState) Stale() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stale")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Stale indicates an expected call of Stale.
func (mr *MockRequestStateMockRecorder) Stale() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stale", reflect.TypeOf((*MockRequestState)(nil).Stale))
}

// XHR mocks base method.
func (m *MockRequestState) XHR() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XHR")
	ret0, _ := ret[0].(bool)
	return ret0
}

// XHR indicates an expected call of XHR.
func (mr *MockRequestStateMockRecorder) XHR() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XHR", reflect.TypeOf((*MockRequestState)(nil).XHR))
}

// MockLocalsStorage is a mock of LocalsStorage interface.
type MockLocalsStorage struct {
	ctrl     *gomock.Controller
	recorder *MockLocalsStorageMockRecorder
	isgomock struct{}
}

// MockLocalsStorageMockRecorder is the mock recorder for MockLocalsStorage.
type MockLocalsStorageMockRecorder struct {
	mock *MockLocalsStorage
}

// NewMockLocalsStorage creates a new mock instance.
func NewMockLocalsStorage(ctrl *gomock.Controller) *MockLocalsStorage {
	mock := &MockLocalsStorage{ctrl: ctrl}
	mock.recorder = &MockLocalsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocalsStorage) EXPECT() *MockLocalsStorageMockRecorder {
	return m.recorder
}

// GetAllLocals mocks base method.
func (m *MockLocalsStorage) GetAllLocals() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLocals")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetAllLocals indicates an expected call of GetAllLocals.
func (mr *MockLocalsStorageMockRecorder) GetAllLocals() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLocals", reflect.TypeOf((*MockLocalsStorage)(nil).GetAllLocals))
}

// Locals mocks base method.
func (m *MockLocalsStorage) Locals(key string, value ...any) any {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range value {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Locals", varargs...)
	ret0, _ := ret[0].(any)
	return ret0
}

// Locals indicates an expected call of Locals.
func (mr *MockLocalsStorageMockRecorder) Locals(key any, value ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, value...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locals", reflect.TypeOf((*MockLocalsStorage)(nil).Locals), varargs...)
}

// MockShorthandResponder is a mock of ShorthandResponder interface.
type MockShorthandResponder struct {
	ctrl     *gomock.Controller
	recorder *MockShorthandResponderMockRecorder
	isgomock struct{}
}

// MockShorthandResponderMockRecorder is the mock recorder for MockShorthandResponder.
type MockShorthandResponderMockRecorder struct {
	mock *MockShorthandResponder
}

// NewMockShorthandResponder creates a new mock instance.
func NewMockShorthandResponder(ctrl *gomock.Controller) *MockShorthandResponder {
	mock := &MockShorthandResponder{ctrl: ctrl}
	mock.recorder = &MockShorthandResponderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShorthandResponder) EXPECT() *MockShorthandResponderMockRecorder {
	return m.recorder
}

// BadRequestMsg mocks base method.
func (m *MockShorthandResponder) BadRequestMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BadRequestMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// BadRequestMsg indicates an expected call of BadRequestMsg.
func (mr *MockShorthandResponderMockRecorder) BadRequestMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BadRequestMsg", reflect.TypeOf((*MockShorthandResponder)(nil).BadRequestMsg), message)
}

// Created mocks base method.
func (m *MockShorthandResponder) Created(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Created", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Created indicates an expected call of Created.
func (mr *MockShorthandResponderMockRecorder) Created(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Created", reflect.TypeOf((*MockShorthandResponder)(nil).Created), data)
}

// ForbiddenMsg mocks base method.
func (m *MockShorthandResponder) ForbiddenMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForbiddenMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForbiddenMsg indicates an expected call of ForbiddenMsg.
func (mr *MockShorthandResponderMockRecorder) ForbiddenMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForbiddenMsg", reflect.TypeOf((*MockShorthandResponder)(nil).ForbiddenMsg), message)
}

// InternalErrorMsg mocks base method.
func (m *MockShorthandResponder) InternalErrorMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalErrorMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// InternalErrorMsg indicates an expected call of InternalErrorMsg.
func (mr *MockShorthandResponderMockRecorder) InternalErrorMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalErrorMsg", reflect.TypeOf((*MockShorthandResponder)(nil).InternalErrorMsg), message)
}

// NoContent mocks base method.
func (m *MockShorthandResponder) NoContent() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoContent")
	ret0, _ := ret[0].(error)
	return ret0
}

// NoContent indicates an expected call of NoContent.
func (mr *MockShorthandResponderMockRecorder) NoContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoContent", reflect.TypeOf((*MockShorthandResponder)(nil).NoContent))
}

// NotFoundMsg mocks base method.
func (m *MockShorthandResponder) NotFoundMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotFoundMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotFoundMsg indicates an expected call of NotFoundMsg.
func (mr *MockShorthandResponderMockRecorder) NotFoundMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotFoundMsg", reflect.TypeOf((*MockShorthandResponder)(nil).NotFoundMsg), message)
}

// OK mocks base method.
func (m *MockShorthandResponder) OK(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OK", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// OK indicates an expected call of OK.
func (mr *MockShorthandResponderMockRecorder) OK(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OK", reflect.TypeOf((*MockShorthandResponder)(nil).OK), data)
}

// UnauthorizedMsg mocks base method.
func (m *MockShorthandResponder) UnauthorizedMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnauthorizedMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnauthorizedMsg indicates an expected call of UnauthorizedMsg.
func (mr *MockShorthandResponderMockRecorder) UnauthorizedMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnauthorizedMsg", reflect.TypeOf((*MockShorthandResponder)(nil).UnauthorizedMsg), message)
}

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
	isgomock struct{}
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// Accepts mocks base method.
func (m *MockContext) Accepts(offers ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Accepts", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Accepts indicates an expected call of Accepts.
func (mr *MockContextMockRecorder) Accepts(offers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accepts", reflect.TypeOf((*MockContext)(nil).Accepts), offers...)
}

// AcceptsCharsets mocks base method.
func (m *MockContext) AcceptsCharsets(offers ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptsCharsets", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// AcceptsCharsets indicates an expected call of AcceptsCharsets.
func (mr *MockContextMockRecorder) AcceptsCharsets(offers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptsCharsets", reflect.TypeOf((*MockContext)(nil).AcceptsCharsets), offers...)
}

// AcceptsEncodings mocks base method.
func (m *MockContext) AcceptsEncodings(offers ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptsEncodings", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// AcceptsEncodings indicates an expected call of AcceptsEncodings.
func (mr *MockContextMockRecorder) AcceptsEncodings(offers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptsEncodings", reflect.TypeOf((*MockContext)(nil).AcceptsEncodings), offers...)
}

// AcceptsLanguages mocks base method.
func (m *MockContext) AcceptsLanguages(offers ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offers {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AcceptsLanguages", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// AcceptsLanguages indicates an expected call of AcceptsLanguages.
func (mr *MockContextMockRecorder) AcceptsLanguages(offers ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptsLanguages", reflect.TypeOf((*MockContext)(nil).AcceptsLanguages), offers...)
}

// AllParams mocks base method.
func (m *MockContext) AllParams() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllParams")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// AllParams indicates an expected call of AllParams.
func (mr *MockContextMockRecorder) AllParams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllParams", reflect.TypeOf((*MockContext)(nil).AllParams))
}

// AllQueries mocks base method.
func (m *MockContext) AllQueries() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllQueries")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// AllQueries indicates an expected call of AllQueries.
func (mr *MockContextMockRecorder) AllQueries() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllQueries", reflect.TypeOf((*MockContext)(nil).AllQueries))
}

// Append mocks base method.
func (m *MockContext) Append(field string, values ...string) {
	m.ctrl.T.Helper()
	varargs := []any{field}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Append", varargs...)
}

// Append indicates an expected call of Append.
func (mr *MockContextMockRecorder) Append(field any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{field}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockContext)(nil).Append), varargs...)
}

// BadRequestMsg mocks base method.
func (m *MockContext) BadRequestMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BadRequestMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// BadRequestMsg indicates an expected call of BadRequestMsg.
func (mr *MockContextMockRecorder) BadRequestMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BadRequestMsg", reflect.TypeOf((*MockContext)(nil).BadRequestMsg), message)
}

// BaseURL mocks base method.
func (m *MockContext) BaseURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseURL indicates an expected call of BaseURL.
func (mr *MockContextMockRecorder) BaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseURL", reflect.TypeOf((*MockContext)(nil).BaseURL))
}

// Body mocks base method.
func (m *MockContext) Body() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Body indicates an expected call of Body.
func (mr *MockContextMockRecorder) Body() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockContext)(nil).Body))
}

// BodyParser mocks base method.
func (m *MockContext) BodyParser(out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BodyParser", out)
	ret0, _ := ret[0].(error)
	return ret0
}

// BodyParser indicates an expected call of BodyParser.
func (mr *MockContextMockRecorder) BodyParser(out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BodyParser", reflect.TypeOf((*MockContext)(nil).BodyParser), out)
}

// ClearCookie mocks base method.
func (m *MockContext) ClearCookie(key ...string) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range key {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ClearCookie", varargs...)
}

// ClearCookie indicates an expected call of ClearCookie.
func (mr *MockContextMockRecorder) ClearCookie(key ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCookie", reflect.TypeOf((*MockContext)(nil).ClearCookie), key...)
}

// Context mocks base method.
func (m *MockContext) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockContextMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockContext)(nil).Context))
}

// Cookie mocks base method.
func (m *MockContext) Cookie(cookie *core.Cookie) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cookie", cookie)
}

// Cookie indicates an expected call of Cookie.
func (mr *MockContextMockRecorder) Cookie(cookie any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cookie", reflect.TypeOf((*MockContext)(nil).Cookie), cookie)
}

// Cookies mocks base method.
func (m *MockContext) Cookies(key string, defaultValue ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range defaultValue {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Cookies", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Cookies indicates an expected call of Cookies.
func (mr *MockContextMockRecorder) Cookies(key any, defaultValue ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, defaultValue...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cookies", reflect.TypeOf((*MockContext)(nil).Cookies), varargs...)
}

// Created mocks base method.
func (m *MockContext) Created(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Created", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Created indicates an expected call of Created.
func (mr *MockContextMockRecorder) Created(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Created", reflect.TypeOf((*MockContext)(nil).Created), data)
}

// ForbiddenMsg mocks base method.
func (m *MockContext) ForbiddenMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForbiddenMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForbiddenMsg indicates an expected call of ForbiddenMsg.
func (mr *MockContextMockRecorder) ForbiddenMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForbiddenMsg", reflect.TypeOf((*MockContext)(nil).ForbiddenMsg), message)
}

// Fresh mocks base method.
func (m *MockContext) Fresh() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fresh")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Fresh indicates an expected call of Fresh.
func (mr *MockContextMockRecorder) Fresh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fresh", reflect.TypeOf((*MockContext)(nil).Fresh))
}

// Get mocks base method.
func (m *MockContext) Get(key string, defaultValue ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range defaultValue {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockContextMockRecorder) Get(key any, defaultValue ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, defaultValue...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockContext)(nil).Get), varargs...)
}

// GetAllLocals mocks base method.
func (m *MockContext) GetAllLocals() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllLocals")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetAllLocals indicates an expected call of GetAllLocals.
func (mr *MockContextMockRecorder) GetAllLocals() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllLocals", reflect.TypeOf((*MockContext)(nil).GetAllLocals))
}

// Hostname mocks base method.
func (m *MockContext) Hostname() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hostname")
	ret0, _ := ret[0].(string)
	return ret0
}

// Hostname indicates an expected call of Hostname.
func (mr *MockContextMockRecorder) Hostname() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hostname", reflect.TypeOf((*MockContext)(nil).Hostname))
}

// IP mocks base method.
func (m *MockContext) IP() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IP")
	ret0, _ := ret[0].(string)
	return ret0
}

// IP indicates an expected call of IP.
func (mr *MockContextMockRecorder) IP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IP", reflect.TypeOf((*MockContext)(nil).IP))
}

// InternalErrorMsg mocks base method.
func (m *MockContext) InternalErrorMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalErrorMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// InternalErrorMsg indicates an expected call of InternalErrorMsg.
func (mr *MockContextMockRecorder) InternalErrorMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalErrorMsg", reflect.TypeOf((*MockContext)(nil).InternalErrorMsg), message)
}

// IsMethod mocks base method.
func (m *MockContext) IsMethod(method string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMethod", method)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMethod indicates an expected call of IsMethod.
func (mr *MockContextMockRecorder) IsMethod(method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMethod", reflect.TypeOf((*MockContext)(nil).IsMethod), method)
}

// JSON mocks base method.
func (m *MockContext) JSON(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JSON", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// JSON indicates an expected call of JSON.
func (mr *MockContextMockRecorder) JSON(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JSON", reflect.TypeOf((*MockContext)(nil).JSON), data)
}

// Locals mocks base method.
func (m *MockContext) Locals(key string, value ...any) any {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range value {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Locals", varargs...)
	ret0, _ := ret[0].(any)
	return ret0
}

// Locals indicates an expected call of Locals.
func (mr *MockContextMockRecorder) Locals(key any, value ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, value...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locals", reflect.TypeOf((*MockContext)(nil).Locals), varargs...)
}

// Method mocks base method.
func (m *MockContext) Method() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Method")
	ret0, _ := ret[0].(string)
	return ret0
}

// Method indicates an expected call of Method.
func (mr *MockContextMockRecorder) Method() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Method", reflect.TypeOf((*MockContext)(nil).Method))
}

// Next mocks base method.
func (m *MockContext) Next() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(error)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockContextMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockContext)(nil).Next))
}

// NoContent mocks base method.
func (m *MockContext) NoContent() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoContent")
	ret0, _ := ret[0].(error)
	return ret0
}

// NoContent indicates an expected call of NoContent.
func (mr *MockContextMockRecorder) NoContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoContent", reflect.TypeOf((*MockContext)(nil).NoContent))
}

// NotFoundMsg mocks base method.
func (m *MockContext) NotFoundMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotFoundMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotFoundMsg indicates an expected call of NotFoundMsg.
func (mr *MockContextMockRecorder) NotFoundMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotFoundMsg", reflect.TypeOf((*MockContext)(nil).NotFoundMsg), message)
}

// OK mocks base method.
func (m *MockContext) OK(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OK", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// OK indicates an expected call of OK.
func (mr *MockContextMockRecorder) OK(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OK", reflect.TypeOf((*MockContext)(nil).OK), data)
}

// OriginalURL mocks base method.
func (m *MockContext) OriginalURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OriginalURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// OriginalURL indicates an expected call of OriginalURL.
func (mr *MockContextMockRecorder) OriginalURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OriginalURL", reflect.TypeOf((*MockContext)(nil).OriginalURL))
}

// Params mocks base method.
func (m *MockContext) Params(key string, defaultValue ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range defaultValue {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Params", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Params indicates an expected call of Params.
func (mr *MockContextMockRecorder) Params(key any, defaultValue ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, defaultValue...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Params", reflect.TypeOf((*MockContext)(nil).Params), varargs...)
}

// ParamsParser mocks base method.
func (m *MockContext) ParamsParser(out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParamsParser", out)
	ret0, _ := ret[0].(error)
	return ret0
}

// ParamsParser indicates an expected call of ParamsParser.
func (mr *MockContextMockRecorder) ParamsParser(out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParamsParser", reflect.TypeOf((*MockContext)(nil).ParamsParser), out)
}

// Path mocks base method.
func (m *MockContext) Path() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockContextMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockContext)(nil).Path))
}

// Protocol mocks base method.
func (m *MockContext) Protocol() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Protocol")
	ret0, _ := ret[0].(string)
	return ret0
}

// Protocol indicates an expected call of Protocol.
func (mr *MockContextMockRecorder) Protocol() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Protocol", reflect.TypeOf((*MockContext)(nil).Protocol))
}

// Query mocks base method.
func (m *MockContext) Query(key string, defaultValue ...string) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range defaultValue {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Query indicates an expected call of Query.
func (mr *MockContextMockRecorder) Query(key any, defaultValue ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, defaultValue...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockContext)(nil).Query), varargs...)
}

// QueryParser mocks base method.
func (m *MockContext) QueryParser(out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryParser", out)
	ret0, _ := ret[0].(error)
	return ret0
}

// QueryParser indicates an expected call of QueryParser.
func (mr *MockContextMockRecorder) QueryParser(out any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryParser", reflect.TypeOf((*MockContext)(nil).QueryParser), out)
}

// Redirect mocks base method.
func (m *MockContext) Redirect(location string, status ...int) error {
	m.ctrl.T.Helper()
	varargs := []any{location}
	for _, a := range status {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Redirect", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Redirect indicates an expected call of Redirect.
func (mr *MockContextMockRecorder) Redirect(location any, status ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{location}, status...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redirect", reflect.TypeOf((*MockContext)(nil).Redirect), varargs...)
}

// RequestID mocks base method.
func (m *MockContext) RequestID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestID")
	ret0, _ := ret[0].(string)
	return ret0
}

// RequestID indicates an expected call of RequestID.
func (mr *MockContextMockRecorder) RequestID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestID", reflect.TypeOf((*MockContext)(nil).RequestID))
}

// ResponseStatusCode mocks base method.
func (m *MockContext) ResponseStatusCode() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResponseStatusCode")
	ret0, _ := ret[0].(int)
	return ret0
}

// ResponseStatusCode indicates an expected call of ResponseStatusCode.
func (mr *MockContextMockRecorder) ResponseStatusCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResponseStatusCode", reflect.TypeOf((*MockContext)(nil).ResponseStatusCode))
}

// RoutePath mocks base method.
func (m *MockContext) RoutePath() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoutePath")
	ret0, _ := ret[0].(string)
	return ret0
}

// RoutePath indicates an expected call of RoutePath.
func (mr *MockContextMockRecorder) RoutePath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoutePath", reflect.TypeOf((*MockContext)(nil).RoutePath))
}

// Secure mocks base method.
func (m *MockContext) Secure() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secure")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Secure indicates an expected call of Secure.
func (mr *MockContextMockRecorder) Secure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secure", reflect.TypeOf((*MockContext)(nil).Secure))
}

// SendBytes mocks base method.
func (m *MockContext) SendBytes(b []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendBytes", b)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendBytes indicates an expected call of SendBytes.
func (mr *MockContextMockRecorder) SendBytes(b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendBytes", reflect.TypeOf((*MockContext)(nil).SendBytes), b)
}

// SendString mocks base method.
func (m *MockContext) SendString(s string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendString", s)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendString indicates an expected call of SendString.
func (mr *MockContextMockRecorder) SendString(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendString", reflect.TypeOf((*MockContext)(nil).SendString), s)
}

// Set mocks base method.
func (m *MockContext) Set(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", key, value)
}

// Set indicates an expected call of Set.
func (mr *MockContextMockRecorder) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockContext)(nil).Set), key, value)
}

// Stale mocks base method.
func (m *MockContext) Stale() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stale")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Stale indicates an expected call of Stale.
func (mr *MockContextMockRecorder) Stale() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stale", reflect.TypeOf((*MockContext)(nil).Stale))
}

// Status mocks base method.
func (m *MockContext) Status(status int) core.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", status)
	ret0, _ := ret[0].(core.Context)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockContextMockRecorder) Status(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockContext)(nil).Status), status)
}

// UnauthorizedMsg mocks base method.
func (m *MockContext) UnauthorizedMsg(message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnauthorizedMsg", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnauthorizedMsg indicates an expected call of UnauthorizedMsg.
func (mr *MockContextMockRecorder) UnauthorizedMsg(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnauthorizedMsg", reflect.TypeOf((*MockContext)(nil).UnauthorizedMsg), message)
}

// UseProperHTTPStatus mocks base method.
func (m *MockContext) UseProperHTTPStatus() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UseProperHTTPStatus")
	ret0, _ := ret[0].(bool)
	return ret0
}

// UseProperHTTPStatus indicates an expected call of UseProperHTTPStatus.
func (mr *MockContextMockRecorder) UseProperHTTPStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseProperHTTPStatus", reflect.TypeOf((*MockContext)(nil).UseProperHTTPStatus))
}

// XHR mocks base method.
func (m *MockContext) XHR() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XHR")
	ret0, _ := ret[0].(bool)
	return ret0
}

// XHR indicates an expected call of XHR.
func (mr *MockContextMockRecorder) XHR() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XHR", reflect.TypeOf((*MockContext)(nil).XHR))
}

// XML mocks base method.
func (m *MockContext) XML(data any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "XML", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// XML indicates an expected call of XML.
func (mr *MockContextMockRecorder) XML(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "XML", reflect.TypeOf((*MockContext)(nil).XML), data)
}
