package aurelion

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
)

// GetRequestID retrieves the request ID from the context.
// The request ID is automatically generated by the requestIDMiddleware and stored in Locals.
// It can also be provided via the X-Request-ID header. If no ID exists, returns an empty string.
//
// Input:
//   - ctx: The aurelion.Context to retrieve request ID from
//
// Output:
//   - string: The request ID, or empty string if not found
//
// Example:
//
//	requestID := aurelion.GetRequestID(ctx)
//	if requestID != "" {
//	    logger.Info("Processing request", "request_id", requestID)
//	}
func GetRequestID(ctx Context) string {
	// Try to get from locals first (this is the primary source)
	if id := ctx.Locals(contextKeyRequestID); id != nil {
		if idStr, ok := id.(string); ok {
			return idStr
		}
	}

	// Request ID should already be in locals from middleware
	// If not found, return empty string
	return ""
}

// requestIDMiddleware is an internal middleware that generates and propagates request IDs.
// It checks if a request ID exists in the header, generates a new optimized ID if not,
// and stores it in both the response header and local context for access throughout the request lifecycle.
func requestIDMiddleware() fiber.Handler {
	return func(c *fiber.Ctx) error {
		// Check if request ID already exists in header
		requestID := c.Get(RequestIDHeader)
		if requestID == "" {
			// Generate new UUID v7 (time-ordered for better database indexing)
			// NewV7 can only fail if system clock is invalid, which is extremely rare
			// In such cases, we fall back to UUID v4 as a safety measure
			uuidV7, err := uuid.NewV7()
			if err != nil {
				// Fallback to v4 if v7 generation fails (system clock issue)
				// NewRandom() should never fail in practice, so we don't handle that error
				// If it somehow fails, we'd have bigger system issues
				requestID = uuid.NewString()
			} else {
				requestID = uuidV7.String()
			}
		}

		// Set request ID in response header for client tracking
		c.Set(RequestIDHeader, requestID)

		// Store in locals for easy access by handlers and middleware
		c.Locals(contextKeyRequestID, requestID)

		return c.Next()
	}
}
