package aurelion

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
)

// traceIDMiddleware creates middleware that generates or reuses trace ID from header.
// The trace ID is stored in Locals and can be accessed via GetTraceID.
// Trace ID follows the same pattern as Request ID: UUID v7 (or v4 fallback).
func traceIDMiddleware() fiber.Handler {
	return func(c *fiber.Ctx) error {
		// Check if trace ID is already set in Locals (from previous middleware)
		if existingTraceID := c.Locals(contextKeyTraceID); existingTraceID != nil {
			if idStr, ok := existingTraceID.(string); ok && idStr != "" {
				// Use existing trace ID
				c.Response().Header.Set(TraceIDHeader, idStr)
				return c.Next()
			}
		}

		// Try to get trace ID from request header
		traceID := c.Get(TraceIDHeader)
		if traceID == "" {
			// Also check for common tracing headers
			traceID = c.Get("X-B3-TraceId")
			if traceID == "" {
				traceID = c.Get("traceparent") // W3C Trace Context
				if traceID != "" {
					// Extract trace ID from traceparent format: 00-{trace-id}-{parent-id}-{flags}
					// For simplicity, use the first 32 hex characters as trace ID
					if len(traceID) > 3 && traceID[2] == '-' {
						traceID = traceID[3:35] // Extract trace ID part
					}
				}
			}
		}

		// If no trace ID from header, generate one
		if traceID == "" {
			// Generate new UUID v7 (time-ordered for better database indexing)
			uuidV7, err := uuid.NewV7()
			if err != nil {
				// Fallback to v4 if v7 generation fails (system clock issue)
				traceID = uuid.NewString()
			} else {
				traceID = uuidV7.String()
			}
		}

		// Store trace ID in Locals
		c.Locals(contextKeyTraceID, traceID)

		// Set trace ID in response header for client tracking
		c.Set(TraceIDHeader, traceID)

		return c.Next()
	}
}

// GetTraceID retrieves the trace ID from the context.
// The trace ID is automatically generated by the traceIDMiddleware (similar to request ID) and stored in Locals.
// It can also be provided via the X-Trace-ID, X-B3-TraceId, or traceparent headers.
// If no trace ID exists, returns an empty string.
// Trace ID follows the same pattern as Request ID: UUID v7 (or v4 fallback).
//
// Input:
//   - ctx: The aurelion.Context to retrieve trace ID from
//
// Output:
//   - string: The trace ID, or empty string if not found
//
// Example:
//
//	traceID := aurelion.GetTraceID(ctx)
//	if traceID != "" {
//	    logger.Info("Processing request", "trace_id", traceID)
//	}
func GetTraceID(ctx Context) string {
	// Try to get from locals first (this is the primary source)
	if id := ctx.Locals(contextKeyTraceID); id != nil {
		if idStr, ok := id.(string); ok {
			return idStr
		}
	}
	// Trace ID should already be in locals from middleware
	// If not found, return empty string
	return ""
}
